name: 应用发布流程

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: 检出项目
      uses: actions/checkout@v6

    - name: 使用JDK 1.8 环境
      uses: actions/setup-java@v5
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'gradle'

    - name: 编译release包
      env:
        PWD_GLUT: ${{ secrets.PWD_GLUT }}
      # 使用AndResGuard打包
      run: |
        chmod +x ./gradlew
        ./gradlew reRe
        ./gradlew :app:zipOutputs

    - name: 上传产出物
      uses: actions/upload-artifact@v6
      with:
        name: release-outputs
        path: app/build/outputs.zip

    - name: 创建 GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: 上传渠道包（GitHub）
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/github/release/com.jacknic.glut-github-release.apk
        asset_name: com.jacknic.glut-github-release.apk
        asset_content_type: application/vnd.android.package-archive

    - name: 上传渠道包（应用宝）
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/yyb/release/com.jacknic.glut-yyb-release.apk
        asset_name: com.jacknic.glut-yyb-release.apk
        asset_content_type: application/vnd.android.package-archive

    - name: 上传渠道包（dev）
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: app/build/outputs/apk/dev/release/com.jacknic.glut-dev-release.apk
        asset_name: com.jacknic.glut-dev-release.apk
        asset_content_type: application/vnd.android.package-archive